import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { BuildMetrics } from './types.js';

/**
 * Format duration from milliseconds to human-readable string
 */
export function formatDuration(ms: number): string {
  // Show milliseconds for sub-second durations
  if (ms < 1000) {
    return ms > 0 ? `${ms}ms` : '0s';
  }

  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;

  if (minutes > 0) {
    return `${minutes}m ${remainingSeconds}s`;
  }
  return `${seconds}s`;
}

/**
 * Format cost to dollar string with 4 decimal places
 */
export function formatCost(cost: number): string {
  return `$${cost.toFixed(4)}`;
}

/**
 * Format a number with locale-aware separators
 */
export function formatNumber(num: number): string {
  return num.toLocaleString();
}

/**
 * Generate a timestamped filename for the report
 */
export function generateReportFilename(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  const hour = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  const sec = String(now.getSeconds()).padStart(2, '0');

  return `nimbus-report-${year}-${month}-${day}-${hour}${min}${sec}.md`;
}

/**
 * Generate markdown report content from build metrics
 */
export function generateReportContent(metrics: BuildMetrics): string {
  const timestamp = new Date(metrics.completedAt).toLocaleString();
  const buildStatus = metrics.buildSuccess ? 'Success' : 'Failed';
  const deployStatus = metrics.deploySuccess ? 'Deployed' : 'Failed (using preview)';

  // Build deployment section based on success/failure
  let deploymentSection: string;
  if (metrics.deploySuccess) {
    deploymentSection = `## Output

- **Deployed URL:** ${metrics.deployedUrl}
- **Build ID:** ${metrics.id}`;
  } else {
    deploymentSection = `## Output

- **Preview URL (temporary):** ${metrics.deployedUrl}
- **Build ID:** ${metrics.id}
- **Deployment Error:** ${metrics.deployError || 'Unknown error'}

> **Warning:** Deployment to Cloudflare Pages failed. The preview URL above is temporary and will expire when the sandbox is cleaned up.`;
  }

  return `# Nimbus Build Report

**Generated:** ${timestamp}

## Prompt

> ${metrics.prompt}

## Summary

| Metric | Value |
|--------|-------|
| Model | ${metrics.model} |
| Total Tokens | ${formatNumber(metrics.totalTokens)} |
| Cost | ${formatCost(metrics.cost)} |
| Duration | ${formatDuration(metrics.totalDurationMs)} |
| Files Generated | ${metrics.filesGenerated} |
| Lines of Code | ${formatNumber(metrics.linesOfCode)} |
| Build | ${buildStatus} |
| Deploy | ${deployStatus} |

## Token Usage

| Type | Count |
|------|-------|
| Prompt (input) | ${formatNumber(metrics.promptTokens)} |
| Completion (output) | ${formatNumber(metrics.completionTokens)} |
| **Total** | **${formatNumber(metrics.totalTokens)}** |

## Timing Breakdown

| Phase | Duration |
|-------|----------|
| LLM Generation | ${formatDuration(metrics.llmLatencyMs)} |
| Install | ${formatDuration(metrics.installDurationMs)} |
| Build | ${formatDuration(metrics.buildDurationMs)} |
| Deploy | ${formatDuration(metrics.deployDurationMs)} |
| **Total** | **${formatDuration(metrics.totalDurationMs)}** |

${deploymentSection}

---

*Generated by [Nimbus](https://github.com/dayhaysoos/nimbus)*
`;
}

/**
 * Save the report to a file in the current working directory
 * Returns the filename
 */
export async function saveReport(metrics: BuildMetrics): Promise<string> {
  const filename = generateReportFilename();
  const filepath = path.join(process.cwd(), filename);
  const content = generateReportContent(metrics);

  await fs.writeFile(filepath, content, 'utf-8');

  return filename;
}
